### Import Modules

In [1]:
import polars as pl

## Load Data

In [3]:
terns = pl.read_csv("01_raw_data/2000-2023_ca_least_tern.csv")

## Inspect Data

In [7]:
terns.head(12)

shape: (12, 43)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ year ┆ site_name  ┆ site_name_ ┆ site_name_ ┆ … ┆ last_obser ┆ first_nes ┆ first_chi ┆ first_fle │
│ ---  ┆ ---        ┆ 2013_2018  ┆ 1988_2001  ┆   ┆ ved        ┆ t         ┆ ck        ┆ dge       │
│ i64  ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│      ┆            ┆ str        ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2000 ┆ PITTSBURG  ┆ Pittsburg  ┆ NA_2013_20 ┆ … ┆ 2000-08-05 ┆ 2000-05-2 ┆ 2000-06-1 ┆ 2000-07-0 │
│      ┆ POWER      ┆ Power      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 8         ┆ 8         │
│      ┆ PLANT      ┆ Plant      ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ALBANY     ┆ NA_NO      ┆ Albany     ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│      ┆ CENTRAL    ┆ POLYGON    ┆ Central    ┆   ┆            ┆           ┆           ┆           │
│      ┆ AVE        ┆            ┆ Avenue     ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ALAMEDA    ┆ Alameda    ┆ NA_2013_20 ┆ … ┆ 2000-08-19 ┆ 2000-05-1 ┆ 2000-06-0 ┆ 2000-06-3 │
│      ┆ POINT      ┆ Point      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 7         ┆ 0         │
│ 2000 ┆ KETTLEMAN  ┆ Kettleman  ┆ NA_2013_20 ┆ … ┆ 2000-09-24 ┆ 2000-06-1 ┆ 2000-07-2 ┆ 2000-08-0 │
│      ┆ CITY       ┆            ┆ 18 POLYGON ┆   ┆            ┆ 7         ┆ 2         ┆ 6         │
│ 2000 ┆ OCEANO     ┆ Oceano     ┆ NA_2013_20 ┆ … ┆ 2000-08-30 ┆ 2000-05-2 ┆ 2000-06-2 ┆ 2000-07-1 │
│      ┆ DUNES      ┆ Dunes      ┆ 18 POLYGON ┆   ┆            ┆ 8         ┆ 0         ┆ 3         │
│      ┆ STATE      ┆ State      ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ VEHICULAR  ┆ Vehicular  ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ R…         ┆ R…         ┆            ┆   ┆            ┆           ┆           ┆           │
│ …    ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2000 ┆ SANTA      ┆ Santa      ┆ NA_2013_20 ┆ … ┆ 2000-09-05 ┆ 2000-06-0 ┆ 2000-06-2 ┆ 2000-07-2 │
│      ┆ CLARA      ┆ Clara      ┆ 18 POLYGON ┆   ┆            ┆ 6         ┆ 8         ┆ 4         │
│      ┆ RIVER      ┆ River      ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ MCGRATH    ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ STAT…      ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2000 ┆ ORMOND     ┆ Ormond     ┆ NA_2013_20 ┆ … ┆ null       ┆ 2000-06-0 ┆ 2000-06-2 ┆ 2000-07-1 │
│      ┆ BEACH      ┆ Beach      ┆ 18 POLYGON ┆   ┆            ┆ 8         ┆ 6         ┆ 7         │
│ 2000 ┆ NBVC POINT ┆ NBVC Point ┆ NA_2013_20 ┆ … ┆ 2000-08-12 ┆ 2000-06-0 ┆ 2000-06-2 ┆ 2000-07-1 │
│      ┆ MUGU       ┆ Mugu       ┆ 18 POLYGON ┆   ┆            ┆ 1         ┆ 4         ┆ 6         │
│ 2000 ┆ VENICE     ┆ Venice     ┆ NA_2013_20 ┆ … ┆ 2000-08-20 ┆ 2000-05-2 ┆ null      ┆ null      │
│      ┆ BEACH      ┆ Beach      ┆ 18 POLYGON ┆   ┆            ┆ 9         ┆           ┆           │
│ 2000 ┆ LA HARBOR  ┆ Port of LA ┆ NA_2013_20 ┆ … ┆ 2000-08-20 ┆ 2000-05-1 ┆ 3000-06-0 ┆ 2000-06-2 │
│      ┆            ┆            ┆ 18 POLYGON ┆   ┆            ┆ 0         ┆ 2         ┆ 2         │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [5]:
terns.tail()

shape: (5, 43)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ year ┆ site_name  ┆ site_name_ ┆ site_name_ ┆ … ┆ last_obser ┆ first_nes ┆ first_chi ┆ first_fle │
│ ---  ┆ ---        ┆ 2013_2018  ┆ 1988_2001  ┆   ┆ ved        ┆ t         ┆ ck        ┆ dge       │
│ i64  ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│      ┆            ┆ str        ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2023 ┆ NAVAL      ┆ Naval Base ┆ NA_2013_20 ┆ … ┆ 2023-09-09 ┆ 2023-05-0 ┆ 2023-05-3 ┆ null      │
│      ┆ AMPHIBIOUS ┆ Coronado   ┆ 18 POLYGON ┆   ┆            ┆ 7         ┆ 1         ┆           │
│      ┆ BASE       ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ CORONADO   ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ DSTREET    ┆ D Street   ┆ NA_2013_20 ┆ … ┆ 2023-08-24 ┆ 2023-05-1 ┆ 2023-06-0 ┆ null      │
│      ┆ FILL       ┆ Fill       ┆ 18 POLYGON ┆   ┆            ┆ 2         ┆ 5         ┆           │
│      ┆ SWEETWATER ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ MARSH …    ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ CHULA      ┆ Chula      ┆ NA_2013_20 ┆ … ┆ 2023-09-22 ┆ 2023-05-1 ┆ 2023-06-0 ┆ null      │
│      ┆ VISTA      ┆ Vista      ┆ 18 POLYGON ┆   ┆            ┆ 4         ┆ 5         ┆           │
│      ┆ WILDLIFE   ┆ Wildlife   ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ RESERVE    ┆ Refuge     ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ SOUTH SAN  ┆ Saltworks  ┆ NA_2013_20 ┆ … ┆ 2023-09-22 ┆ 2023-05-1 ┆ 2023-06-0 ┆ null      │
│      ┆ DIEGO BAY  ┆            ┆ 18 POLYGON ┆   ┆            ┆ 9         ┆ 9         ┆           │
│      ┆ UNIT       ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│      ┆ SDNWR…     ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
│ 2023 ┆ TIJUANA    ┆ Tijuana    ┆ NA_2013_20 ┆ … ┆ 2023-08-28 ┆ 2023-05-1 ┆ 2023-06-1 ┆ null      │
│      ┆ ESTUARY    ┆ Estuary    ┆ 18 POLYGON ┆   ┆            ┆ 2         ┆ 0         ┆           │
│      ┆ NERR       ┆            ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [8]:
terns.shape

(791, 43)

In [9]:
terns.columns

['year',
 'site_name',
 'site_name_2013_2018',
 'site_name_1988_2001',
 'site_abbr',
 'region_3',
 'region_4',
 'event',
 'bp_min',
 'bp_max',
 'fl_min',
 'fl_max',
 'total_nests',
 'nonpred_eggs',
 'nonpred_chicks',
 'nonpred_fl',
 'nonpred_ad',
 'pred_control',
 'pred_eggs',
 'pred_chicks',
 'pred_fl',
 'pred_ad',
 'pred_pefa',
 'pred_coy_fox',
 'pred_meso',
 'pred_owlspp',
 'pred_corvid',
 'pred_other_raptor',
 'pred_other_avian',
 'pred_misc',
 'total_pefa',
 'total_coy_fox',
 'total_meso',
 'total_owlspp',
 'total_corvid',
 'total_other_raptor',
 'total_other_avian',
 'total_misc',
 'first_observed',
 'last_observed',
 'first_nest',
 'first_chick',
 'first_fledge']